=== gmega/god/GOD_Console_Prototype_1/dtd/attributespec.dtd
<?xml version='1.0' encoding='ASCII'?>

<!ELEMENT spec ((attribute|extension-attribute)+)>
<!ATTLIST spec 
	name	CDATA					#REQUIRED
	type	CDATA				 	#REQUIRED 
>

<!ELEMENT attribute EMPTY>
<!ATTLIST attribute
	id	CDATA	#REQUIRED
>

<!ELEMENT extension-attribute EMPTY>
<!ATTLIST extension-attribute
	id		CDATA	#REQUIRED
	action	CDATA	#REQUIRED
>

=== gmega/god/GOD_Console_Prototype_1/specs/ddproto1.launcher.JVMShellLauncher.launcherspec.xml
<?xml version="1.0" encoding="ASCII"?>
<!DOCTYPE spec SYSTEM "dtd/attributespec.dtd">

<spec name="Java Virtual Machine Shell Launcher (bash syntax)" type="launcher">
	<attribute id="main-class"/>
	<attribute id="classpath"/>
	<attribute id="jdwp-port"/>
	<attribute id="vm-parameters"/>
	<attribute id="app-parameters"/>
	<attribute id="tunnel-closure-policy"/>
	
	<child type="shell-tunnel"/>
	
</spec>

=== gmega/god/GOD_Console_Prototype_1/specs/JVMShellLauncher.launcherspec.xml
<?xml version="1.0" encoding="ASCII"?>
<!DOCTYPE spec SYSTEM "dtd/attributespec.dtd">

<spec name="Java Virtual Machine Shell Launcher (bash syntax)" type="ddproto1.launcher.JVMShellLauncher">
	<attribute id="main-class"/>
	<attribute id="classpath"/>
	<attribute id="jdwp-port"/>
	<attribute id="vm-parameters"/>
	<attribute id="app-parameters"/>
	<attribute id="tunnel-closure-policy"/>
	
	<child id="tunnel"/>
	
</spec>

=== gmega/god/GOD_Console_Prototype_1/specs/ddproto1.launcher.JVMShellLauncher.tunnelledlauncherspec.xml
<?xml version="1.0" encoding="ASCII"?>
<!DOCTYPE spec SYSTEM "dtd/attributespec.dtd">

<spec name="Java Virtual Machine Shell Launcher (bash syntax)" type="tunnelled-launcher">
	<attribute id="main-class"/>
	<attribute id="classpath"/>
	<attribute id="jdwp-port" default-value="#context"/>
	<attribute id="cdwp-port" default-value="#context"/>
	<attribute id="global-agent-address" default-value="#context"/>
	<attribute id="vm-parameters"/>
	<attribute id="app-parameters"/>
	<attribute id="tunnel-closure-policy"/>
	<attribute id="local-agent-jar"/>
	<attribute id="log4j-config-url" default-value="auto"/>
	
	<!-- Ideal would be:
		<extension-attribute id="CORBA-enabled" 
							action="yes:loadspec(CORBAJava, launcher);no:nop()" 
							default-value="#context"/>
		
		and that would cause the launcher to try to infer the value of attribute
		CORBA-enabled from the context of its parent.
	-->
	<attribute id="guid" default-value="#context"/>
		
	<child type="shell-tunnel" multiplicity="1"/>
</spec>
